
/* Listen for message */
chrome.runtime.onMessage.addListener(
	function(request, sender, sendResponse){
		// if message matches, call pickNewCountry function
		if (request.greeting == "This is a request") {
			var result = pickNewCountry();
			console.log("Request received. Country picked is " + result.name);
			// send response back to override.js
			sendResponse({result});
		}
	});

/* Uses random number generator to pick a random country from list */
function pickNewCountry(){
	// create JSON Object to store country information
	var $countryObj = { "countries": [
		{"name":"Afghanistan", "pop":"32.53 Million", "url":"Afghanistan", "link":"http://tinyurl.com/zbwtb8u", "author":"Ricardo Mangual", "cc":"",
			"facts":["fun","great"]},
		{"name":"Albania", "pop":"2.89 Million", "url": "Albania", "link":"http://tinyurl.com/glmecmx", "author":"Websi", "cc":"",
			"facts":["kinda fun","kinda great"]},
		{"name":"Algeria", "pop":"39.67 Million", "url":"Algeria", "link":"http://tinyurl.com/gktdetz", "author":"Hichem Merouche", "cc":"",
			"facts":["a","b"]},
		{"name":"Andorra", "pop":"70,000", "url":"Andorra", "link":"http://tinyurl.com/j3c2nks", "author":"Miquel Fabre", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Angola", "pop":"25.02 Million", "url":"Angola", "link":"http://tinyurl.com/z3g84us", "author":"jbdodane", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Antigua and Barbuda", "pop":"91,000", "url":"Antigua+and+Barbuda", "link":"http://tinyurl.com/gwmwf8e", "author":"Andrew Moore", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Argentina", "pop":"43.42 Million", "url":"Argentina", "link":"http://tinyurl.com/hxjz3zx", "author":"marc cornelis", "cc":"", 
			"facts":["a","b"]},
		{"name":"Armenia", "pop":"3.02 Million", "url":"Armenia", "link":"http://tinyurl.com/jpm4mvg", "author":"Dmitry", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Australia", "pop":"23.78 Million", "url":"Australia", "link":"http://tinyurl.com/z8to2bf", "author":"Lenny K Photography", "cc":"", 
			"facts":["a","b"]},
		{"name":"Austria", "pop":"8.61 Million", "url":"Austria", "link":"http://tinyurl.com/gum5v3w", "author":"Bernd Thaller", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Azerbaijan", "pop":"9.65 Million", "url":"Azerbaijan", "link":"http://tinyurl.com/hts4tww", "author":"Bs0u10e0", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"Bahamas", "pop":"388,000", "url":"Bahamas", "link":"http://tinyurl.com/zy46lj6", "author":"photos_mweber", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Bahrain", "pop":"1.38 Million", "url":"Bahrain", "link":"http://tinyurl.com/zypvq8u", "author":"Wacky Toyo Boy Borj", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Bangladesh", "pop":"161 Million", "url":"Bangladesh", "link":"http://tinyurl.com/zn8y62h", "author":"Aftab Uzzaman", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Barbados", "pop":"284,000", "url":"Barbados", "link":"http://tinyurl.com/gtj9bym", "author":"Tuukka Rantamäki", "cc":"", 
			"facts":["a","b"]},
		{"name":"Belarus", "pop":"9.51 Million", "url":"Belarus", "link":"http://tinyurl.com/gtc52rg", "author":"Viktor Kirilko", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Belgium", "pop":"11.29 Million", "url":"Belgium", "link":"http://tinyurl.com/h4rmy5v", "author":"RobinTphoto", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Belize", "pop":"359,000", "url":"Belize", "link":"http://tinyurl.com/jextc8p", "author":"f. ermert", "cc":"", 
			"facts":["a","b"]},
		{"name":"Benin", "pop":"10.88 Million", "url":"Benin", "link":"http://tinyurl.com/gtxtw6r", "author":"Shubert Ciencia", "cc":"", 
			"facts":["a","b"]},
		{"name":"Bhutan", "pop":"774,000", "url":"Bhutan", "link":"http://tinyurl.com/zyev425", "author":"Inga Vitola", "cc":"", 
			"facts":["a","b"]},
		{"name":"Bolivia", "pop":"10.72 Million", "url":"Bolivia", "link":"http://tinyurl.com/zf6au6m", "author":"roman korzh", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Bosnia and Herzegovina", "pop":"3.81 Million", "url":"Bosnia+and+Herzegovina", "link":"http://tinyurl.com/gt9as4b", "author":"Ivana Vasilj", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Botswana", "pop":"2.26 Million", "url":"Botswana", "link":"http://tinyurl.com/j8hwfzu", "author":"Aftab Uzzaman", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Brazil", "pop":"207.85 Million", "url":"Brazil", "link":"http://tinyurl.com/hesyhux", "author":"SF Brit", "cc":"", 
			"facts":["a","b"]},
		{"name":"Brunei", "pop":"423,000", "url":"Brunei", "link":"http://tinyurl.com/gl4asxs", "author":"henrykkcheung", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Bulgaria", "pop":"7.18 Million", "url":"Bulgaria", "link":"http://tinyurl.com/gmef6gz", "author":"Dennis Jarvis", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"Burkina Faso", "pop":"18.11 Million", "url":"Burkina+Faso", "link":"http://tinyurl.com/h4a82zg", "author":"Guillaume Colin & Pauline Penot", "cc":"", 
			"facts":["a","b"]},
		{"name":"Burma (Myanmar)", "pop":"53.9 Million", "url":"Burma", "link":"http://tinyurl.com/hkakcws", "author":"Alexander Mueller", "cc":"", 
			"facts":["a","b"]},
		{"name":"Burundi", "pop":"11.18 Million", "url":"Burundi", "link":"http://tinyurl.com/zcrqhat", "author":"Christine Vaufrey", "cc":"", 
			"facts":["a","b"]},
		{"name":"Cabo Verde", "pop":"520,000", "url":"Cabo+Verde", "link":"http://tinyurl.com/glh4nvr", "author":"Caroline Granycome", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"Cambodia", "pop":"15.58 Million", "url":"Cambodia", "link":"http://tinyurl.com/gl64r4t", "author":"Fougerouse Arnaud", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Cameroon", "pop":"23.34 Million", "url":"Cameroon", "link":"http://tinyurl.com/j4j3egw", "author":"Ludwig Tröller", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Canada", "pop":"35.85 Million", "url":"Canada", "link":"http://tinyurl.com/hfz6pag", "author":"Thank you for visiting my page", "cc":"", 
			"facts":["a","b"]},
		{"name":"Central African Republic", "pop":"4.9 Million", "url":"Central+African+Republic", "link":"http://tinyurl.com/hneakg7", "author":"LM TP", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Chad", "pop":"14.04 Million", "url":"Chad", "link":"http://tinyurl.com/zmmyulp", "author":"David Stanley", "cc":"", 
			"facts":["a","b"]},
		{"name":"Chile", "pop":"17.95 Million", "url":"Chile", "link":"http://tinyurl.com/z9jbml7", "author":"Mariano Mantel", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"China", "pop":"1.37 Billion", "url":"China", "link":"http://tinyurl.com/z2crn2n", "author":"dove lee", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Colombia", "pop":"48.23 Million", "url":"Colombia", "link":"http://tinyurl.com/je7u4hg", "author":"Alexander Schimmeck", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Comoros", "pop":"788,000", "url":"Comoros", "link":"http://tinyurl.com/hkglwdk", "author":"Chamara Irugalratne", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Democratic Republic of the Congo", "pop":"77.27 Million", "url":"Democratic+Republic+of+the+Congo", "link":"http://tinyurl.com/jr5hbws", "author":"Tom Jutte", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Republic of the Congo", "pop":"4.62 Million", "url":"Republic+of+the+Congo", "link":"http://tinyurl.com/hbzfqh3", "author":"Paul Godard", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Costa Rica", "pop":"4.81 Million", "url":"Costa+Rica", "link":"http://tinyurl.com/go6ffs3", "author":"Ralph Earlandson", "cc":"-nc-sa", 
			"facts":["a","b"]},
		{"name":"Cote d'Ivoire", "pop":"22.7 Million", "url":"Cote+dIvoire", "link":"http://tinyurl.com/gsewwhw", "author":"Guillaume Mignot", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Croatia", "pop":"4.22 Million", "url":"Croatia", "link":"http://tinyurl.com/zcqag9g", "author":"Erin Johnson", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Cuba", "pop":"11.39 Million", "url":"Cuba", "link":"http://tinyurl.com/jorf8vf", "author":"Bud Ellison", "cc":"", 
			"facts":["a","b"]},
		{"name":"Cyprus", "pop":"1.17 Million", "url":"Cyprus", "link":"http://tinyurl.com/gp5jtev", "author":"Tobias Van Der Elst", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"Czechia", "pop":"10.55 Million", "url":"Czechia", "link":"http://tinyurl.com/h5xdbo5", "author":"Nico Trinkhaus", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Denmark", "pop":"5.68 Million", "url":"Denmark", "link":"http://tinyurl.com/h5gzpce", "author":"Jacob Surland", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Djibouti", "pop":"888,000", "url":"Djibouti", "link":"http://tinyurl.com/hgekvav", "author":"DVIDSHUB", "cc":"", 
			"facts":["a","b"]},
		{"name":"Dominica", "pop":"73,000", "url":"Dominica", "link":"http://tinyurl.com/heexzcx", "author":"Matthias Ripp", "cc":"", 
			"facts":["a","b"]},
		{"name":"Dominican Republic", "pop":"10.53 Million", "url":"Dominican+Republic", "link":"http://tinyurl.com/z7r2yh3", "author":"Joe deSousa", "cc":"", 
			"facts":["a","b"]},
		{"name":"Ecuador", "pop":"16.14 Million", "url":"Ecuador", "link":"http://tinyurl.com/hdm65ok", "author":"- Adam Reeder -", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Egypt", "pop":"91.51 Million", "url":"Egypt", "link":"http://tinyurl.com/hkgunwy", "author":"Edgardo W. Olivera", "cc":"", 
			"facts":["a","b"]},
		{"name":"El Salvador", "pop":"845,000", "url":"El+Salvador", "link":"http://tinyurl.com/jg97xwo", "author":"Javier Suay Anton", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Equatorial Guinea", "pop":"35.85 Million", "url":"Equatorial+Guinea", "link":"http://tinyurl.com/jqjrud5", "author":"NathanaelStanek", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Eritrea", "pop":"4.79 Million", "url":"Eritrea", "link":"http://tinyurl.com/gnqrnvp", "author":"Clay Gilliland", "cc":"-sa", 
			"facts":["a","b"]}, // pop as of 2011
		{"name":"Estonia", "pop":"1.31 Million", "url":"Estonia", "link":"http://tinyurl.com/zgvmhu5", "author":"Anita", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Ethiopia", "pop":"99.39 Million", "url":"Ethiopia", "link":"http://tinyurl.com/zbl9alh", "author":"Indrik myneur", "cc":"", 
			"facts":["a","b"]},
		{"name":"Fiji", "pop":"892,000", "url":"Fiji", "link":"http://tinyurl.com/hjmls6q", "author":"kyle post", "cc":"", 
			"facts":["a","b"]},
		{"name":"Finland", "pop":"5.48 Million", "url":"Finland", "link":"http://tinyurl.com/hu6ydau", "author":"Timo Newton-Syms", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"France", "pop":"66.81 Million", "url":"France", "link":"http://tinyurl.com/gsr2d3z", "author":"Vincent Brassinne", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Gabon", "pop":"1.73 Million", "url":"Gabon", "link":"http://tinyurl.com/zt7mvww", "author":"jbdodane", "cc":"-nc", 
			"facts":["a","b"]},
		{"name":"Gambia", "pop":"1.99 Million", "url":"Gambia", "link":"http://tinyurl.com/h4qt4qy", "author":"Dunlop Marshall Photos", "cc":"-nc-nd", 
			"facts":["a","b"]},
		{"name":"Georgia", "pop":"3.68 Million", "url":"Georgia", "link":"http://tinyurl.com/hnzjzsg", "author":"Gill M L", "cc":"-sa", 
			"facts":["a","b"]},
		{"name":"Germany", "pop":"81.41 Million", "url":"Germany", "link":"http://tinyurl.com/zzh7wrk", "author":"Markus Jaschke", "cc":"-nc",  
			"facts":["a","b"]},
		{"name":"Ghana", "pop":"27.41 Million", "url":"Ghana", "link":"http://tinyurl.com/h6ursla", "author":"hiroo yamagata", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Greece", "pop":"10.82 Million", "url":"Greece", "link":"http://tinyurl.com/hcwoso2", "author":"Rafal Zych", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Grenada", "pop":"107,000", "url":"Grenada", "link":"http://tinyurl.com/zks87l5", "author":"David Kirsch", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Guatemala", "pop":"16.34 Million", "url":"Guatemala", "link":"http://tinyurl.com/z5qnsgn", "author":"Dave Wilson", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Guinea", "pop":"12.61 Million", "url":"Guinea", "link":"http://tinyurl.com/jmcj4al", "author":"Peter Linehan", "cc":"",
			"facts":["a","b"]},
		{"name":"Guinea-Bissau", "pop":"1.84 Million", "url":"Guinea-Bissau", "link":"http://tinyurl.com/jmxl7eo", "author":"LM TP", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Guyana", "pop":"767,000", "url":"Guyana", "link":"http://tinyurl.com/z8rxfta", "author":"Stefan Krasowski", "cc":"",
			"facts":["a","b"]},
		{"name":"Haiti", "pop":"10.71 Million", "url":"Haiti", "link":"http://tinyurl.com/z8l7hs8", "author":"Steve Bennett", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Honduras", "pop":"8.08 Million", "url":"Honduras", "link":"http://tinyurl.com/zvlojh9", "author":"Carl", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Hungary", "pop":"9.84 Million", "url":"Hungary", "link":"http://tinyurl.com/ze8fc53", "author":"RobinTphoto", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Iceland", "pop":"331,000", "url":"Iceland", "link":"http://tinyurl.com/z94qks2", "author":"Andrés Nieto Porras", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"India", "pop":"1.31 Billion", "url":"India", "link":"http://tinyurl.com/gmmf4xs", "author":"sandeepachetan.com travel photography", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Indonesia", "pop":"257.56 Million", "url":"Indonesia", "link":"http://tinyurl.com/hnapk75", "author":"Matthias Ripp", "cc":"",
			"facts":["a","b"]},
		{"name":"Iran", "pop":"79.11 Million", "url":"Iran", "link":"http://tinyurl.com/jmyeya8", "author":"Michael Foley", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Iraq", "pop":"36.42 Million", "url":"Iraq", "link":"http://tinyurl.com/jvey75u", "author":"Jayel Aheram", "cc":"",
			"facts":["a","b"]},
		{"name":"Ireland", "pop":"4.64 Million", "url":"Ireland", "link":"http://tinyurl.com/zfrzjrf", "author":"Giuseppe Milo", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Israel", "pop":"8.38 Million", "url":"Israel", "link":"http://tinyurl.com/zeoa9p7", "author":"amira_a", "cc":"",
			"facts":["a","b"]},
		{"name":"Italy", "pop":"60.8 Million", "url":"Italy", "link":"http://tinyurl.com/z5xzu4w", "author":"Giuseppe Milo", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Jamaica", "pop":"2.73 Million", "url":"Jamaica", "link":"http://tinyurl.com/jhvh9lp", "author":"smilla4", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Japan", "pop":"126.96 Million", "url":"Japan", "link":"http://tinyurl.com/jdsmkgl", "author":"Yoshikazu TAKADA", "cc":"",
			"facts":["a","b"]},
		{"name":"Jordan", "pop":"7.59 Million", "url":"Jordan", "link":"http://tinyurl.com/hptchw7", "author":"Rob Oo", "cc":"",
			"facts":["a","b"]},
		{"name":"Kazakhstan", "pop":"17.54 Million", "url":"Kazakhstan", "link":"http://tinyurl.com/z4jpddf", "author":"mariusz kluzniak", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Kenya", "pop":"46.05 Million", "url":"Kenya", "link":"http://tinyurl.com/jzhdw7y", "author":"Benh LIEU SONG", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Kiribati", "pop":"112,000", "url":"Kiribati", "link":"http://tinyurl.com/jfeogyz", "author":"Nick Hobgood", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Kosovo", "pop":"1.8 Million", "url":"Kosovo", "link":"http://tinyurl.com/jtraso2", "author":"Vegim Zhitija", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Kuwait", "pop":"3.89 Million", "url":"Kuwait", "link":"http://tinyurl.com/hugklr8", "author":"Tamer Habib", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Kyrgyzstan", "pop":"5.96 Million", "url":"Kyrgyzstan", "link":"http://tinyurl.com/j4pzfxq", "author":"Mzximvs VdB", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Laos", "pop":"6.8 Million", "url":"Laos", "link":"http://tinyurl.com/zd3lv8d", "author":"Mild Delirium", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Latvia", "pop":"1.98 Million", "url":"Latvia", "link":"http://tinyurl.com/hlsfn3w", "author":"Māris Pehlaks", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Lebanon", "pop":"5.85 Million", "url":"Lebanon", "link":"http://tinyurl.com/zfr9t63", "author":"Paul Saad", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Lesotho", "pop":"2.14 Million", "url":"Lesotho", "link":"http://tinyurl.com/gnsqgcz", "author":"John Karwoski", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Liberia", "pop":"4.5 Million", "url":"Liberia", "link":"http://tinyurl.com/zu5b6ra", "author":"jbdodane", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Libya", "pop":"6.28 Million", "url":"Libya", "link":"http://tinyurl.com/z34lxl8", "author":"Stéphane Toumayan (ToumaŸ)", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Liechtenstein", "pop":"38,000", "url":"Liechtenstein", "link":"http://tinyurl.com/gpp4zd6", "author":"Norlando Pobre", "cc":"",
			"facts":["a","b"]},
		{"name":"Lithuania", "pop":"2.91 Million", "url":"Lithuania", "link":"http://tinyurl.com/jtrcmux", "author":"Mantas Volungevicius", "cc":"",
			"facts":["a","b"]},
		{"name":"Luxembourg", "pop":"570,000", "url":"Luxembourg", "link":"http://tinyurl.com/zwfjr6m", "author":"Wolfgang Staudt", "cc":"",
			"facts":["a","b"]},
		{"name":"Macedonia", "pop":"2.08 Million", "url":"Macedonia", "link":"http://tinyurl.com/jlalkjt", "author":"Marjan Lazarevski", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Madagascar", "pop":"24.24 Million", "url":"Madagascar", "link":"http://tinyurl.com/z88obcq", "author":"mariusz kluzniak", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Malawi", "pop":"17.22 Million", "url":"Malawi", "link":"http://tinyurl.com/jtz4mql", "author":"Jack Zalium", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Malaysia", "pop":"30.33 Million", "url":"Malaysia", "link":"http://tinyurl.com/zchcyd2", "author":"Ah Wei (Lung Wei)", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Maldives", "pop":"409,000", "url":"Maldives", "link":"http://tinyurl.com/hjqwjag", "author":"Mac Qin", "cc":"-nd",
			"facts":["a","b"]},
		{"name":"Mali", "pop":"17.6 Million", "url":"Mali", "link":"http://tinyurl.com/zf895jy", "author":"Johannes Zielcke", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Malta", "pop":"431,000", "url":"Malta", "link":"http://tinyurl.com/jobb2jl", "author":"Giuseppe Milo", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Marshall Islands", "pop":"53,000", "url":"Marshall+Islands", "link":"http://tinyurl.com/jqwldvt", "author":"Keith Polya", "cc":"",
			"facts":["a","b"]},
		{"name":"Mauritania", "pop":"4.07 Million", "url":"Mauritania", "link":"http://tinyurl.com/jbts3mr", "author":"Christophe André", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Mauritius", "pop":"1.26 Million", "url":"Mauritius", "link":"http://tinyurl.com/ju76cwy", "author":"Fougerouse Arnaud", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Mexico", "pop":"127.02 Million", "url":"Mexico", "link":"http://tinyurl.com/j9jc6jn", "author":"Katie Schumm", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Micronesia", "pop":"104,000", "url":"Micronesia", "link":"http://tinyurl.com/zcnghnu", "author":"NASA's Marshall Space Flight Center", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Moldova", "pop":"3.55 Million", "url":"Moldova", "link":"http://tinyurl.com/z8s8kaf", "author":"michieru", "cc":"",
			"facts":["a","b"]},
		{"name":"Monaco", "pop":"37,000", "url":"Monaco", "link":"http://tinyurl.com/zaubbyq", "author":"Ricardo", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Mongolia", "pop":"2.96 Million", "url":"Mongolia", "link":"http://tinyurl.com/zqb6cao", "author":"Rob Oo", "cc":"",
			"facts":["a","b"]},
		{"name":"Montenegro", "pop":"622,000", "url":"Montenegro", "link":"http://tinyurl.com/znnhu3p", "author":"dаrii", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Morocco", "pop":"34.38 Million", "url":"Morocco", "link":"http://tinyurl.com/h6trmoe", "author":"Thomas Maluck", "cc":"-nd",
			"facts":["a","b"]},
		{"name":"Mozambique", "pop":"27.98 Million", "url":"Mozambique", "link":"http://tinyurl.com/zwezn5t", "author":"Stig Nygaard", "cc":"",
			"facts":["a","b"]},
		{"name":"Namibia", "pop":"2.46 Million", "url":"Namibia", "link":"http://tinyurl.com/hjttd3t", "author":"Aftab Uzzaman", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Nauru", "pop":"10,000", "url":"Nauru", "link":"http://tinyurl.com/j9svjr6", "author":"Public.Resource.Org", "cc":"",
			"facts":["a","b"]},
		{"name":"Nepal", "pop":"28.51 Million", "url":"Nepal", "link":"http://tinyurl.com/hvew68v", "author":"Mild Delirium", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Netherlands", "pop":"16.94 Million", "url":"Netherlands", "link":"http://tinyurl.com/h58zswv", "author":"mariusz kluzniak", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"New Zealand", "pop":"4.6 Million", "url":"New+Zealand", "link":"http://tinyurl.com/jqwrqjm", "author":"Roberto Saltori", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Nicaragua", "pop":"6.08 Million", "url":"Nicaragua", "link":"http://tinyurl.com/jjbsxty", "author":"ashokboghani", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Niger", "pop":"19.9 Million", "url":"Niger", "link":"http://tinyurl.com/zyj333s", "author":"Gustave Deghilage", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Nigeria", "pop":"182.2 Million", "url":"Nigeria", "link":"http://tinyurl.com/hul3tqd", "author":"Mark Fischer", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"North Korea", "pop":"25.15 Million", "url":"North+Korea", "link":"http://tinyurl.com/zab7bpp", "author":"Clay Gilliland", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Norway", "pop":"5.2 Million", "url":"Norway", "link":"http://tinyurl.com/jmc9l6z", "author":"Giuseppe Milo", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Oman", "pop":"4.49 Million", "url":"Oman", "link":"http://tinyurl.com/hvk86h8", "author":"Matteo Russo", "cc":"",
			"facts":["a","b"]},
		{"name":"Pakistan", "pop":"188.92 Million", "url":"Pakistan", "link":"http://tinyurl.com/jzrzwn2", "author":"umer malik", "cc":"-nc-sa",
			"facts":["a","b"]},
		{"name":"Palau", "pop":"21,000", "url":"Palau", "link":"http://tinyurl.com/guj5eov", "author":"LuxTonnerre", "cc":"",
			"facts":["a","b"]},
		{"name":"Panama", "pop":"3.93 Million", "url":"Panama", "link":"http://tinyurl.com/gvebgzy", "author":"f. ermert", "cc":"",
			"facts":["a","b"]},
		{"name":"Papua New Guinea", "pop":"7.62 Million", "url":"Papua+New+Guinea", "link":"http://tinyurl.com/hge2l8t", "author":"Stefan Krasowski", "cc":"",
			"facts":["a","b"]},
		{"name":"Paraguay", "pop":"6.64 Million", "url":"Paraguay", "link":"http://tinyurl.com/h3czk4y", "author":"Alejandro Valdez Sanabria", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Peru", "pop":"31.38 Million", "url":"Peru", "link":"http://tinyurl.com/j9o2wyk", "author":"Art DiNo", "cc":"-sa",
			"facts":["a","b"]},
		{"name":"Philippines", "pop":"100.7 Million", "url":"Philippines", "link":"http://tinyurl.com/jq92g8r", "author":"Loïc Lagarde", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Poland", "pop":"38 Million", "url":"Poland", "link":"http://tinyurl.com/zoevqo2", "author":"Rafal Zych", "cc":"-nc-nd",
			"facts":["a","b"]},
		{"name":"Portugal", "pop":"10.35 Million", "url":"Portugal", "link":"http://tinyurl.com/jcoesll", "author":"Giuseppe Milo", "cc":"-nc",
			"facts":["a","b"]},
		{"name":"Qatar", "pop":"2.24 Million", "url":"Qatar", "link":" ", "author":"Derek Bruff", "cc":"",
			"facts":["a","b"]},
		{"name":"Romania", "pop":"19.83 Million", "url":"Romania", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Russia", "pop":"144.1 Million", "url":"Russia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Rwanda", "pop":"11.61 Million", "url":"Rwanda", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Saint Kitts and Nevis", "pop":"56,000", "url":"Saint+Kitts+and+Nevis", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Saint Lucia", "pop":"185,000", "url":"Saint+Lucia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Saint Vincent and the Grenadines", "pop":"109,000", "url":"Saint+Vincent+and+the+Grenadines", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Samoa", "pop":"193,000", "url":"Samoa", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"San Marino", "pop":"32,000", "url":"San+Marino", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Sao Tome and Principe", "pop":"190,000", "url":"Sao+Tome+and+Principe", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Saudi Arabia", "pop":"31.54 Million", "url":"Saudi+Arabia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Senegal", "pop":"15.13 Million", "url":"Senegal", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Serbia", "pop":"7.1 Million", "url":"Serbia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Seychelles", "pop":"93,000", "url":"Seychelles", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Sierra Leone", "pop":"6.45 Million", "url":"Sierra+Leone", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Singapore", "pop":"5.54 Million", "url":"Singapore", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Slovakia", "pop":"5.42 Million", "url":"Slovakia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Slovenia", "pop":"2.06 Million", "url":"Slovenia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Solomon Islands", "pop":"584,000", "url":"Solomon+Islands", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Somalia", "pop":"10.79 Million", "url":"Somalia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"South Africa", "pop":"54.96 Million", "url":"South+Africa", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"South Korea", "pop":"50.62 Million", "url":"South+Korea", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"South Sudan", "pop":"12.34 Million", "url":"South+Sudan", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Spain", "pop":"46.42 Million", "url":"Spain", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Sri Lanka", "pop":"20.97 Million", "url":"Sri+Lanka", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Sudan", "pop":"40.23 Million", "url":"Sudan", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Suriname", "pop":"543,000", "url":"Suriname", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Swaziland", "pop":"1.29 Million", "url":"Swaziland", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Sweden", "pop":"9.8 Million", "url":"Sweden", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Switzerland", "pop":"8.29 Million", "url":"Switzerland", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Syria", "pop":"18.5 Million", "url":"Syria", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Tajikistan", "pop":"8.48 Million", "url":"Tajikistan", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Tanzania", "pop":"53.47 Million", "url":"Tanzania", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Thailand", "pop":"67.96 Million", "url":"Thailand", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Timor-Leste", "pop":"1.25 Million", "url":"Timor-Leste", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Togo", "pop":"7.3 Million", "url":"Togo", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Tonga", "pop":"160,000", "url":"Tonga", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Trinidad and Tobago", "pop":"1.36 Million", "url":"Trinidad+and+Tobago", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Tunisia", "pop":"11.11 Million", "url":"Tunisia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Turkey", "pop":"78.67 Million", "url":"Turkey", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Turkmenistan", "pop":"5.37 Million", "url":"Turkmenistan", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Tuvalu", "pop":"10,000", "url":"Tuvalu", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Uganda", "pop":"39.03 Million", "url":"Uganda", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Ukraine", "pop":"45.2 Million", "url":"Ukraine", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"United Arab Emirates", "pop":"9.16 Million", "url":"United+Arab+Emirates", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"United Kingdom", "pop":"65.14 Million", "url":"United+Kingdom", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"United States of America", "pop":"321.42 Million", "url":"United+States+of+America", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Uruguay", "pop":"3.43 Million", "url":"Uruguay", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Uzbekistan", "pop":"31.3 Million", "url":"Uzbekistan", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Vanuatu", "pop":"265,000", "url":"Vanuatu", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Vatican City", "pop":"451", "url":"Vatican+City", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]}, // pop 2012 http://data.un.org/Data.aspx?d=POP&f=tableCode%3A240
		{"name":"Venezuela", "pop":"31.12 Million", "url":"Venezuela", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Vietnam", "pop":"91.7 Million", "url":"Vietnam", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Yemen", "pop":"26.83 Million", "url":"Yemen", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Zambia", "pop":"16.21 Million", "url":"Zambia", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		{"name":"Zimbabwe", "pop":"15.6 Million", "url":"Zimbabwe", "link":" ", "author":" ", "cc":"",
			"facts":["a","b"]},
		]
	};

/*
	var countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", 
	"Antigua+and+Barbuda", "Argentina", "Armenia", "Australia", "Austria", 
	"Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", 
	"Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia+and+Herzegovina", 
	"Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina+Faso", "Burma", "Burundi", 
	"Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central+African+Republic", "Chad", 
	"Chile", "China", "Colombia", "Comoros", "Democratic+Republic+of+the+Congo", 
	"Republic+of+the+Congo", "Costa+Rica", "Cote+d'Ivoire", "Croatia", "Cuba", "Cyprus", 
	"Czechia", "Denmark", "Djibouti", "Dominica", "Dominican+Republic", "Ecuador", 
	"Egypt", "El+Salvador", "Equatorial+Guinea", "Eritrea", "Estonia", "Ethiopia", 
	"Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", 
	"Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", 
	"Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", 
	"Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", 
	"Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", 
	"Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", 
	"Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall+Islands", "Mauritania", 
	"Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", 
	"Morocco", "Mozambique", "Namibia", "Nauru", "Nepal", "Netherlands", "New+Zealand", 
	"Nicaragua", "Niger", "Nigeria", "North+Korea", "Norway", "Oman", "Pakistan", "Palau", 
	"Panama", "Papua+New+Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", 
	"Qatar", "Romania", "Russia", "Rwanda", "Saint+Kitts+and+Nevis", "Saint+Lucia", 
	"Saint+Vincent+and+the+Grenadines", "Samoa", "San+Marino", "Sao+Tome+and+Principe", 
	"Saudi+Arabia", "Senegal", "Serbia", "Seychelles", "Sierra+Leone", "Singapore", 
	"Slovakia","Slovenia", "Solomon+Islands", "Somalia", "South+Africa", "South+Korea", 
	"South+Sudan", "Spain", "Sri+Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", 
	"Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo",
	"Tonga", "Trinidad+and+Tobago", "Tunisia", "Turkey", "Turkmenistan", "Tuvalu", "Uganda",
	"Ukraine", "United+Arab+Emirates", "United+Kingdom", "United+States+of+America", 
	"Uruguay", "Uzbekistan", "Vanuatu", "Vatican+City", "Venezuela", "Vietnam", "Yemen", 
	"Zambia", "Zimbabwe"];
*/
	// pick a number
	//var randNum = numberGenerator($countryObj.countries.length);
	var randNum = numberGenerator(26);
	//var randFact = numberGenerator(countryObj.countries[randNum].facts.length);
	//var randImg = numberGenerator(countryObj.countries[randNum].url.length);
	// search country on google maps 
	//console.log(countries[randNumber]);

	$countryObj.countries["factNum"] = numberGenerator($countryObj.countries[randNum].facts.length); // MIGHT HAVE TO DO IN OVERRIDE.JS

	console.log("Length is " + $countryObj.countries.length);
	console.log("Fact is " + $countryObj.countries[randNum].facts[$countryObj.countries.factNum]);

	// CHANGE THIS AT END TO randNum
	return $countryObj.countries[139];
	//chrome.tabs.update(null, {url: "http://google.com/maps/place/" + countries[randNumber]});
}

// function numberGenerator returns number between 0-194 
// Need to implement with variable parameter
function numberGenerator(n) {
	return Math.floor(Math.random() * n);

	//return Math.floor(Math.random() * 29);
	//return Math.floor(Math.random() * 195);
}

/* Maybe this function is not needed 
function changeBackground(){
	console.log("change background func");
	//document.body.style.backgroundImage = "url(" + pickNewCountry() + ".jpg)";
	alert(document.body.style.backgroundImage);
	return "United+States";
}
*/


